name: Atividade 1
type: dart
steps:
  - name: Exercício 1
    directory: step_01
    has_solution: true
  - name: Exercício 2
    directory: step_02
    has_solution: true
  # - name: Step 2
  #   directory: step_02
  #   has_solution: false